name: Gerar APK LUCROCEL

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Corrigir permissão do Gradlew
        run: chmod +x gradlew

      - name: Fabricar o APK (Debug)
        run: ./gradlew assembleDebug --stacktrace

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: LUCROCEL-App-Instalador
          path: app/build/outputs/apk/debug/app-debug.apk
